version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    restart: always
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
